wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1635436874
    t:
      1:
      - 3
      4: 3.9.7
      5: 0.12.5
      8:
      - 5
